coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1
    patch:
      default:
        target: 50%
  notify:
    wait_for_ci: true
  range: 80..100
  github_checks:
    annotations: false
  comment:
    after_n_builds: 30
